version: '3'
services:
  app:
    container_name: morse-code-ninja
    build: .
    volumes:
      - .:/opt/morse-code-ninja/
    environment:
      - AWS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
